import { confirm, select } from "./prompts";

/**
 * A project "profile" picks which shape of app gets scaffolded. Every
 * profile shares one base (the "full-backend" template tree itself —
 * `template/`): a non-full-backend profile is generated by copying that
 * base, then deleting the files it doesn't need (`profiles/<id>/remove.txt`)
 * and layering its own files on top (`profiles/<id>/files/`). See
 * `packages/create-wrap/profiles/README.md` for the full mechanics.
 *
 * "full-backend" itself has no remove/files directory — it doesn't need
 * one, it's not a diff from anything — but it does have two yes/no
 * follow-ups (Redis cache, realtime websockets) applied as small text
 * edits to the copied template rather than a whole alternate file set,
 * since they're each a single conditional block.
 */
export type ProfileId =
  | "full-backend"
  | "lightweight-api"
  | "api-aggregator"
  | "fullstack-ssr"
  | "gateway";

export interface ProfileDefinition {
  id: ProfileId;
  label: string;
  hint: string;
}

export const PROFILES: ProfileDefinition[] = [
  {
    id: "full-backend",
    label: "Full backend",
    hint: "Postgres + Drizzle, Redis cache, realtime websockets, auth — everything",
  },
  {
    id: "lightweight-api",
    label: "Lightweight API / auth-only",
    hint: "no DB, no cache, no realtime — routes + auth + OpenAPI docs",
  },
  {
    id: "api-aggregator",
    label: "External API aggregator",
    hint: "no DB — services that call out to other APIs, fronted by controllers",
  },
  {
    id: "fullstack-ssr",
    label: "Fullstack SSR",
    hint: "Hono + TanStack Router + React, server-rendered (no DB by default)",
  },
  {
    id: "gateway",
    label: "Proxy / gateway",
    hint: "HTTP reverse-proxy (hono/proxy) + best-effort WebSocket proxy",
  },
];

export interface ProfileAnswers {
  profile: ProfileId;
  /** full-backend only. */
  enableRedisCache: boolean;
  /** full-backend only. */
  enableRealtime: boolean;
}

/** Runs the interactive profile + follow-up prompts. */
export async function promptForAnswers(): Promise<ProfileAnswers> {
  const profile = await select<ProfileId>(
    "What kind of project is this?",
    PROFILES.map((p) => ({ value: p.id, label: p.label, hint: p.hint })),
  );

  let enableRedisCache = false;
  let enableRealtime = false;

  if (profile === "full-backend") {
    enableRedisCache = await confirm(
      "Enable the Redis cache backend? (in-memory cache is always available either way)",
      true,
    );
    enableRealtime = await confirm(
      "Enable realtime websockets (entity events fanned out over /realtime)?",
      true,
    );
  }

  return { profile, enableRedisCache, enableRealtime };
}
